server:
  port: 6000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: taiChiMan-crowd-order
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.125
  session:
    store-type: redis